// Package wildduck is a REST client for a WildDuck mail server
// (github.com/zone-eu/wildduck) — the real mail stack this box runs
// (WildDuck + Haraka + ZoneMTA + a bundled webmail), reached over its
// local, token-authenticated HTTP API rather than by editing config
// files the way internal/mail's Postfix/Dovecot code did. WildDuck's
// API only ever needs to be reached from this same host (it binds
// 127.0.0.1:8080), so every call here is plain HTTP, not HTTPS — same
// "local socket is the trust boundary" posture internal/dbmanager and
// internal/mail's own IMAP client already take.
package wildduck

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// tokenFileName is where this host's WildDuck API token is kept —
// Kursor-owned, root-only, same lifecycle as every other
// LoadOrGenerate*-style secret file in this codebase (mail's own
// master password, the VPN install key, ...). Unlike those, this one
// is NOT generated by Kursor itself: WildDuck's own api.toml has to be
// configured with the exact same value first (this host's was set by
// hand during its install), so a missing file here means "the
// integration hasn't been wired up yet," not "generate a fresh one" —
// generating our own would just never match what WildDuck's config
// actually expects.
const tokenFileName = "wildduck_api_token"

// ErrNotConfigured means no token file was found — the caller should
// show a clear "not connected yet" state rather than a raw HTTP error.
var ErrNotConfigured = errors.New("wildduck: API token not configured (see internal/wildduck package docs)")

// LoadAPIToken reads this host's WildDuck API token.
func LoadAPIToken(dataDir string) (string, error) {
	b, err := os.ReadFile(filepath.Join(dataDir, tokenFileName))
	if err != nil {
		if os.IsNotExist(err) {
			return "", ErrNotConfigured
		}
		return "", err
	}
	token := strings.TrimSpace(string(b))
	if token == "" {
		return "", ErrNotConfigured
	}
	return token, nil
}

// Client talks to one WildDuck instance.
type Client struct {
	baseURL string
	token   string
	http    *http.Client
}

// NewClient builds a Client for the WildDuck API — baseURL is normally
// "http://127.0.0.1:8080" (WildDuck's own default bind address).
func NewClient(baseURL, token string) *Client {
	return &Client{
		baseURL: strings.TrimSuffix(baseURL, "/"),
		token:   token,
		http:    &http.Client{Timeout: 10 * time.Second},
	}
}

// apiError is WildDuck's own error envelope — surfaced verbatim in Go
// errors so an admin sees WildDuck's real complaint (e.g. "This user
// already exists"), not a paraphrase. Confirmed live against a real
// WildDuck instance: {"code":"InvalidToken","message":"..."}, i.e. the
// human-readable text is in "message", not "error".
type apiError struct {
	Message string `json:"message"`
	Code    string `json:"code"`
}

func (c *Client) do(method, path string, body any, out any) error {
	var reqBody io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		reqBody = bytes.NewReader(b)
	}
	req, err := http.NewRequest(method, c.baseURL+path, reqBody)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	if c.token != "" {
		req.Header.Set("X-Access-Token", c.token)
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	if resp.StatusCode >= 400 {
		var apiErr apiError
		if json.Unmarshal(data, &apiErr) == nil && apiErr.Message != "" {
			return fmt.Errorf("wildduck: %s", apiErr.Message)
		}
		return fmt.Errorf("wildduck: HTTP %d: %s", resp.StatusCode, string(data))
	}
	if out != nil {
		return json.Unmarshal(data, out)
	}
	return nil
}

// User is one WildDuck mailbox account — the fields this integration
// actually uses, not WildDuck's full user object.
type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
	Address  string `json:"address"`
	Quota    struct {
		Allowed int64 `json:"allowed"`
		Used    int64 `json:"used"`
	} `json:"quota"`
	Disabled bool `json:"disabled"`
}

// CreateUser provisions a real WildDuck mailbox — username is the
// login name (no @domain), address is the full email address (which
// can be on a different domain than the derived default, since
// WildDuck lets you set it explicitly at creation).
func (c *Client) CreateUser(username, password, address, name string) (id string, err error) {
	var result struct {
		Success bool   `json:"success"`
		ID      string `json:"id"`
	}
	err = c.do(http.MethodPost, "/users", map[string]any{
		"username": username,
		"password": password,
		"address":  address,
		"name":     name,
	}, &result)
	if err != nil {
		return "", err
	}
	return result.ID, nil
}

// ListUsers returns every mailbox on this WildDuck instance.
func (c *Client) ListUsers() ([]User, error) {
	var result struct {
		Results []User `json:"results"`
	}
	if err := c.do(http.MethodGet, "/users?limit=250", nil, &result); err != nil {
		return nil, err
	}
	return result.Results, nil
}

// GetUser fetches one mailbox by its WildDuck id.
func (c *Client) GetUser(id string) (*User, error) {
	var u User
	if err := c.do(http.MethodGet, "/users/"+id, nil, &u); err != nil {
		return nil, err
	}
	return &u, nil
}

// ResetPassword sets a mailbox's password.
func (c *Client) ResetPassword(id, newPassword string) error {
	return c.do(http.MethodPut, "/users/"+id, map[string]any{"password": newPassword}, nil)
}

// SetDisabled enables/disables a mailbox without deleting it — mirrors
// this codebase's usual reversible-disable pattern (VPN peers, cron
// jobs, ...) rather than only offering an irreversible delete.
func (c *Client) SetDisabled(id string, disabled bool) error {
	return c.do(http.MethodPut, "/users/"+id, map[string]any{"disabled": disabled}, nil)
}

// DeleteUser permanently removes a mailbox and its stored mail.
func (c *Client) DeleteUser(id string) error {
	return c.do(http.MethodDelete, "/users/"+id, nil, nil)
}
